### ISSUE TITLE
Make a datapack only version

### ISSUE THREAD

**Issue by dandud100** [TreeOfSelf/CarpetSkyAdditions-Reborn#1]
Would like to use the wordgen with structures and biome boundaries on an server running on papermc, is it possible to make a datapack out of this?

**Comment by dandud100** [comment]
> If you are just looking for a datapack to generate a void world with structure and biome bounding boxes, use this https://modrinth.com/datapack/skyblock-void-worldgen
> 
> If you want this mod, with all of its features, as a datapack that is sadly not possible because not all of the features of this mod are able to be put into a datapack.

Thanks for the hint! Sadly that linked datapack does not generate all structures that exist in minecraft but only a few selected.

**Comment by TreeOfSelf** [comment]
You might be able to edit 
[get_empty_biomes.py](https://github.com/BluePsychoRanger/SkyBlock_Collection/blob/main/src/plugins/worldgen/get_empty_biomes.py) and 
[get_empty_structures.py](https://github.com/BluePsychoRanger/SkyBlock_Collection/blob/main/src/plugins/worldgen/get_empty_structures.py)
and run generate.py to get the biomes & structures you want.

**Comment by dandud100** [comment]
> You might be able to edit [get_empty_biomes.py](https://github.com/BluePsychoRanger/SkyBlock_Collection/blob/main/src/plugins/worldgen/get_empty_biomes.py) and [get_empty_structures.py](https://github.com/BluePsychoRanger/SkyBlock_Collection/blob/main/src/plugins/worldgen/get_empty_structures.py) and run generate.py to get the biomes & structures you want.

Thanks for pointing that out, but sadly i never created a plugin or datapack by myself. So no Idea what to change there.

**Comment by TreeOfSelf** [comment]
It's outside of the scope of this project, because the worldgen in CarpetSkyAdditions isn't in datapack format, it's coded using Fabric API.
