### ISSUE TITLE
1.21.4 Implementation Ideas 

### ISSUE THREAD

**Issue by TreeOfSelf** [TreeOfSelf/CarpetSkyAdditions-Reborn#13]
Now that the creaking update is out, how should it be implemented into CarpetSkyAdditions?

**Comment by DrKhaoticSarcasm** [comment]
Maybe grow an open eyeblossom near the pale oak sapling to get a creaking heart variant? similar how you grow saplings near flowers to get beehives?

**Comment by Seigmannen** [comment]
Good idea. Maybe even make it necessary to do this in the pale garden biome, to make it a little harder.

**Comment by TreeOfSelf** [comment]
> Maybe grow an open eyeblossom near the pale oak sapling to get a creaking heart variant? similar how you grow saplings near flowers to get beehives?
> 
> Because you can get eyeblossoms and pale oak saplings from wandering trader by default.

[Implemented](https://github.com/TreeOfSelf/CarpetSkyAdditions-Reborn/commit/58fb4f6059563717156cdecbb9fef000d5f274ca)
