### ISSUE TITLE
Build failed due to mismatched class type from Carpet "Explosion_optimizedTntMixin"

### ISSUE THREAD

**Issue by Xotsu** [TreeOfSelf/CarpetSkyAdditions-Reborn#15]
Hey, I can't manage to get a clean master clone running after a day of trying, sorry this is probably something incorrect on my end since I'm new to Java development. Please let me know if the logs are insufficient, any help is appreciated, thank you!

Can reproduce:

```
git clone <repo>
cd <repo>
./gradlew gensources build
./gradlew runClient
```
I've also tried the following before running any gradle commands:
```
./gradlew --stop
./gradlew clean --refresh-dependencies
```
Here is the condensed error, unless I'm mistaken it seems the mixin for Carpet `Explosion_optimizedTntMixin` targets `net.minecraft.world.level.Explosion` as a class, but in Minecraft 1.21.3, `Explosion` appears to be an interface:

```
RuntimeException: Mixin transformation of net.minecraft.client.main.Main failed
```

```
MixinApplyError: Mixin [carpet.mixins.json:Explosion_optimizedTntMixin from mod carpet] from phase [DEFAULT] in config
[carpet.mixins.json] FAILED during PREPARE
```
```
InvalidMixinException: @Mixin target type mismatch: net.minecraft.world.level.Explosion is an interface in
org.spongepowered.asm.mixin.transformer.MixinInfo$SubType$Standard@79767781
```

OS: Windows 10

openjdk version "21.0.5" 2024-10-15 LTS
OpenJDK Runtime Environment Temurin-21.0.5+11 (build 21.0.5+11-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.5+11 (build 21.0.5+11-LTS, mixed mode, sharing)

18 mods loaded:
        - carpet 1.4.128+v231205
        - carpetskyadditions 1.21.3-5.1.0
        - cloth-basic-math 0.6.1
        - cloth-config 13.0.114
        - fabric-api-base 0.4.48+2127dc7240
        - fabric-key-binding-api-v1 1.0.40+78d798af4f
        - fabric-lifecycle-events-v1 2.2.29+78d798af4f
        - fabric-networking-api-v1 4.3.3+56ec7ac640
        - fabric-object-builder-api-v1 17.0.7+c47b9d4340
        - fabric-registry-sync-v0 5.2.0+56ec7ac640
        - fabric-resource-loader-v0 3.0.5+c47b9d4340
        - fabric-screen-api-v1 2.0.16+78d798af4f
        - fabric-transitive-access-wideners-v1 6.1.8+c47b9d4340
        - fabricloader 0.16.7
        - java 21
        - minecraft 1.21.3
        - mixinextras 0.4.1
        - modmenu 9.0.0

**Comment by Seigmannen** [comment]
Did you succeed? I can test later if I get the time. Usually I build it and copy the build over to the minecraft mods folder.
I know i'm doing it the slow way.
