### ISSUE TITLE
Issue with Swift sneak

### ISSUE THREAD

**Issue by Seigmannen** [TreeOfSelf/CarpetSkyAdditions-Reborn#17]
There seems to be an issue with the Swift sneak enchant not coming up as an alternative when close to a warden (8 blocks) as intended.
I tried to fix it, but was not able to.
There was no error or anything, it just doesn't seem to be implemented. The settings in carpetskyadditions i s set to true as well.

As a temporary fix I created a loot table for librarians. If they are killed by a warden inside an ancient city, they will drop a random Swift sneak book.

**Comment by TreeOfSelf** [comment]
[Seems to be fixed now?](https://github.com/TreeOfSelf/CarpetSkyAdditions-Reborn/commit/0606b510417a4ecbd7e48d7bd12c5eb2f56e7c97)
thanks for the report
