### ISSUE TITLE
Cannot join on vanilla client

### ISSUE THREAD

**Issue by rylry** [TreeOfSelf/CarpetSkyAdditions-Reborn#19]
I cannot join unless I have carpetSkyAdditions installed.
![image](https://github.com/user-attachments/assets/ae757386-51d3-4086-a086-6b618de4d93d)

From the logs:

[12:42:53] [Render thread/INFO]: Connecting to sky.hardcoreanarchy.gay, 25565
[12:42:54] [Render thread/ERROR]: Received unknown remote registry entries from server
[12:42:54] [Render thread/ERROR]: Registry entry (carpetskyadditions:swift_sneak_enchantable) is missing from local registry (minecraft:data_component_type)
[12:42:54] [Render thread/ERROR]: Registry remapping failed!
java.util.concurrent.CompletionException: net.fabricmc.fabric.impl.registry.sync.RemapException: Received a registry entry that is unknown to this client.
This is usually caused by a mismatched mod set between the client and server. See the client logs for more details.
The following registry entry namespaces may be related:

carpetskyadditions

**Comment by TreeOfSelf** [comment]
Thanks for bringing this to my attention, it actually only requires Fabric, and Fabric API loaded. 
Still- definitely not normal. 

Has to do with a somewhat questionable way jsorrell tagged items as being swift sneak enchantable. I was looking at it as I was fixing it the other day with a bit of a raised eyebrow. Not too surprised to see it causing problems. I'll make it priority to get this fixed and put out a release.

**Comment by TreeOfSelf** [comment]
Addressed here
https://github.com/TreeOfSelf/CarpetSkyAdditions-Reborn/commit/134e9bbf7d9d6f65e414d9dcfcfb31f76460c1ed
Thanks
