### ISSUE TITLE
Generating a stronghold structure crashes the server

### ISSUE THREAD

**Issue by SebbyFur** [TreeOfSelf/CarpetSkyAdditions-Reborn#20]
Generating a stronghold structure crashes the server. Using version 5.2.0. Not tested on earlier versions.

You can reproduce the issue by locating a stronghold with the /locate command, and then teleporting to it. Note that the /place command won't help reproducing the issue since it generates a standard stronghold structure

Full crash report: https://pastebin.com/7F5gxnMy

**Comment by TreeOfSelf** [comment]
Thank you for the detailed report, I will try and have this fixed soon.

**Comment by Xotsu** [comment]
Accidentally encountered this on singe player as well.

**Comment by TreeOfSelf** [comment]
Believe this should be fixed now
https://github.com/TreeOfSelf/CarpetSkyAdditions-Reborn/commit/4768a733b2bca1b1bb85bd284e567fbf55880570
