### ISSUE TITLE
Coral can spread to Calcite.

### ISSUE THREAD

**Issue by Seigmannen** [TreeOfSelf/CarpetSkyAdditions-Reborn#22]
I cannot seem to get this to work anymore. It worked in carpetskyadditions 1.21.1.

When surround a calcite block with 8 coral block in a warm ocean biome, the calcite has a chance to turn into a coral block.
I have tried this for 100 days ingame using tick sprint, and it does not work.

Either it is broken, and not giving any error message, or something has changed and i'm doing it wrong.

**Comment by TreeOfSelf** [comment]
https://github.com/TreeOfSelf/CarpetSkyAdditions-Reborn/commit/8133885f8d0234e60ff101fa6d2e779db132ddec
Fixed thanks
