### ISSUE TITLE
Vex to Allay not working

### ISSUE THREAD

**Issue by Seigmannen** [TreeOfSelf/CarpetSkyAdditions-Reborn#23]
There seems to be an issue with this as well. I see that the vexes indicate a redstone signal when set up as explained by jsorrel. (activator rail and comparator), but when playing the note, nothing happens. And there are no errors.
Anyone else tested this?

**Comment by TreeOfSelf** [comment]
https://github.com/TreeOfSelf/CarpetSkyAdditions-Reborn/commit/c6d2a4b4c4d0f1a581b4835a9ca3232c848ee568
Fixed
