### ISSUE TITLE
Wandering Trader riding a Camel in desert biomes

### ISSUE THREAD

**Issue by Seigmannen** [TreeOfSelf/CarpetSkyAdditions-Reborn#24]
When the wandering trader spawns, the game crashes, when logging back in, the camel has spawned, but the wandering trader is gone, so I guess that is the issue.

Crash Report: [https://pastebin.com/fmTGJfmY](https://pastebin.com/fmTGJfmY)

**Comment by TreeOfSelf** [comment]
Fixed 
https://github.com/TreeOfSelf/CarpetSkyAdditions-Reborn/commit/57cc7180658e6acb09eff0ccbb030347b15c56c2
thanks
