### ISSUE TITLE
Vex to Allay issue.

### ISSUE THREAD

**Issue by Seigmannen** [TreeOfSelf/CarpetSkyAdditions-Reborn#28]
Still have an issue with this one. After the noteblocks played in the correct order (5 times), the game crashes. I guess it is at this time the vex is turning into allay. When logging in again, the vex is loose and attacking (Yikes), and the allay is sitting in the minecart. This is probably an easy fix maybe.

Crash report: [https://pastebin.com/Vh9M15Bv](https://pastebin.com/Vh9M15Bv)

Another thing is the notes from the noteblock. I think it was originally  like this (not a big deal thou):
![2024-12-22_11 14 35](https://github.com/user-attachments/assets/7b26ceb0-939a-4d12-abf4-e0a0f554d3fb)

**Comment by Seigmannen** [comment]
I was able to fix the crash issue. 
I will send a pull request for this.

**Comment by TreeOfSelf** [comment]
thanks!
