### ISSUE TITLE
Can't get into end world it's a serious bug

### ISSUE THREAD

**Issue by ChwnWang0** [TreeOfSelf/CarpetSkyAdditions-Reborn#29]
My World Endgame is inaccessible and the server crashes when you enter it.
I have submitted logs about it.

Error version carpetskyadditions-1.21.3-5.1.0

[crash-2024-12-22_11.47.17-server.txt](https://github.com/user-attachments/files/18221876/crash-2024-12-22_11.47.17-server.txt)

[This feedback uses a translation tool that may have a language barrier]

**Comment by TreeOfSelf** [comment]
Please use latest 1.21.4 release, no support is provided for older versions.
