### ISSUE TITLE
Advancements Reef Builder and Coral Utopia does not trigger.

### ISSUE THREAD

**Issue by Seigmannen** [TreeOfSelf/CarpetSkyAdditions-Reborn#33]
I build a small 3x3 coral "building" with a calcite block in the middle in a warm ocean biome. The coral will spread to the calcite, but the "Reef Builder" achievement did not trigger.
The same with "Coral Utopia". It does not trigger.

I tried to look into it, but cannot figure it out. Any help fixing this would be appreciated.

**Comment by TreeOfSelf** [comment]
Reef Builder has been fixed https://github.com/TreeOfSelf/CarpetSkyAdditions-Reborn/commit/651c35a18a35f5319c4f4d69f74c624d7202a6a1 , mind you, the check works when you place the actual calcite block in a warm ocean, with an appropriate amount of coral nearby.  (is this the best way to do it? probably not, but it is how it worked originally) 

I, at first glance can't really understand how the Coral Utopia one is supposed to work, 
```
   public static double calculateCoralSuitability(ServerLevel level, BlockPos pos) {
        if (!level.dimensionType().equals(BuiltinDimensionTypes.OVERWORLD))  {
            return 0;
        }

        ServerChunkCache chunkCache = level.getChunkSource();
        if (chunkCache.getGenerator() instanceof NoiseBasedChunkGenerator) {
            NoiseRouter noiseRouter = chunkCache.randomState().router();
            DensityFunction.SinglePointContext context =
                    new DensityFunction.SinglePointContext(pos.getX(), pos.getY(), pos.getZ());
            double temp = noiseRouter.temperature().compute(context);
            double continentalness = noiseRouter.continents().compute(context);
            double squaredDifference =
                    (Mth.square(temp - TARGET_TEMP) + Mth.square(continentalness - TARGET_CONTINENTALNESS));
            return Mth.clamp(1 - squaredDifference, 0, 1);
        }
        return 0.5;
    }
```
Something to do with checking the biomes temperature? And it looks like that is what determines how much the coral spreads? It may be fixed, but ill leave this open til we can confirm.

**Comment by TreeOfSelf** [comment]
Seems to have just been this line https://github.com/TreeOfSelf/CarpetSkyAdditions-Reborn/commit/0666bc877d4881180a4d1edada826e0a8e84f6d0 making it always return 0

I believe it is fixed, because I got the advancement and  it showed a reasonable number returned from `calculateCoralSuitability`, but let me know if its not.
