### ISSUE TITLE
Trial Chamber issues.

### ISSUE THREAD

**Issue by Seigmannen** [TreeOfSelf/CarpetSkyAdditions-Reborn#35]
So, I have been testing the trial chambber implementation a little bit. Here are some issues I could find.

1. I need to use two breeze rods to activate the spawner.
2. The spawner loot table seems to be not properly implemented. Normal spawner drops nothing many times, Ominous spawner drops normal trial key.
3. As I can see the spawner spawns about 6 mobs (one player) on normal and ominous. Shouldn't it spawn more mobs when ominous?
4. the ominous vault is opened by normal vault key, and seems to drop (not confirmed) loot from normal vault loot table.
5. I get this error in my log "[Server thread/ERROR]: Trial Spawner at class_2338{x=-10168, y=-15, z=-9959} has no detected players", I think it has something to do with the advancement maybe. The coordinates are the coordinates of the trial spawner.

I think this is enough for now. I hope my findings can be of help to improve the trial chambers even more.

**Comment by TreeOfSelf** [comment]
1. You need to use two breeze rods to activate the spawner? I just tried it and it only took one.
2. As far as dropping nothing, I haven't seen anything like that. What I did see is this [very annoying](https://bugs.mojang.com/browse/MC-273048) thing where Microsoft has decided placing a trial spawner should function differently when ominous than a trial spawner naturally generated. Makes absolutely no sense. I had to go and manually copy the NBT data of a naturally generated vault and trial spawner to figure out how to replicate it properly. https://github.com/TreeOfSelf/CarpetSkyAdditions-Reborn/commit/578aa53c37a510f3dfefa92aabbc5920d61b140c
3.  They have the exact same behavior as they do on vanilla, which you can test by putting a platform for them to spawn on, and then testing an ominous trial chamber on vanilla.
4. Same nonsense as 2 
5. https://github.com/TreeOfSelf/CarpetSkyAdditions-Reborn/commit/f809fe8cab7a37834cac8425fa3b7604f5e57eb7

Let me know if there are any more issues, thanks.

**Comment by TreeOfSelf** [comment]
@Seigmannen  actually, could you let me know if they are good now? I'd like to do a release fixing this if they are.
Thanks.

**Comment by Seigmannen** [comment]
I will test it as soon as I get the opportunity. Probably in a few hours.

**Comment by Seigmannen** [comment]
I have tested it a bit with the updated scripts, and the first thing I see is that the trial spawner is allreade active. No need for breeze rod. The rest seems to be OK.
