### ISSUE TITLE
Creaking Heart generation

### ISSUE THREAD

**Issue by Seigmannen** [TreeOfSelf/CarpetSkyAdditions-Reborn#36]
Not an issue exactly. I tested the implementation with the open eyeblossom and the pale oak sapling, and it works very well. In my opinion a little too well. As I can see from the code it's a 10% chance per log, and it checks a certain range. If my calculations are correct, you get like a 90-95% chance per tree too get a creaking heart.
Just my suggestion, maybe make it 10% chance for creaking heart generation per tree? I was able to fix this on my part. If you want to see, let me know..

**Comment by TreeOfSelf** [comment]
I only put that chance just so it wouldn't always be the same block turning into a creaking heart, but I think making it less likely would also make it so its more similar to how beehives are generated. So feel free to PR it, thanks.

**Comment by TreeOfSelf** [comment]
https://github.com/TreeOfSelf/CarpetSkyAdditions-Reborn/commit/03daa22536474d13e6c82262b580c9abc74d217e 
I just made it a 5% chance to make it closer to what beehives are.
