### ISSUE TITLE
Trial Spawner.

### ISSUE THREAD

**Issue by Seigmannen** [TreeOfSelf/CarpetSkyAdditions-Reborn#38]
Well.. back to the trial spawner.

When using a breeze rod on an inactive trial spawner, it will consume one breeze rod, but nothing happens, except an error message in the log.

[Render thread/ERROR]: Registry does not exist: ResourceKey[minecraft:root / minecraft:trial_spawner]; Registry does not exist: ResourceKey[minecraft:root / minecraft:trial_spawner]

Can anyone else test to see if they get the same result, or if there's something wrong at my side?

Thanks.

**Comment by TreeOfSelf** [comment]
Only happens if you are running it on singleplayer, and is pretty easily fixed just by not running the mixin on the clientisde https://github.com/TreeOfSelf/CarpetSkyAdditions-Reborn/commit/61fd980e45a5381d596516d2e1db3f20ff3beaf6

Since most people are probably going to run it Singleplayer I will need to start testing it there.

**Comment by Seigmannen** [comment]
Thank you. Now it worked perfectly. Now I think I have tested all aspects of the game in single player, and now everything seems to be working nicely.

Maybe time to start testing serverside as well. :p

Thank you for keeping this updated. :)

**Comment by TreeOfSelf** [comment]
Awesome, thanks for your help getting it to this point.

I am considering putting out a separate mod/command that deletes chunks with previously generated trial chamber stuff. My server is littered now with the older ones.

**Comment by Seigmannen** [comment]
I use a tool called [mcaselector](https://github.com/Querz/mcaselector) for deleting chunks.

**Comment by TreeOfSelf** [comment]
Oh that's a good idea, I didn't think of that. Can just use a structure selector. Maybe I just pot the command-line command to do it. Thanks.
