### ISSUE TITLE
Is there 1.21?

### ISSUE THREAD

**Issue by jittb** [TreeOfSelf/CarpetSkyAdditions-Reborn#4]
Not suitable for 1.21,only 1.21.1

**Comment by TreeOfSelf** [comment]
Then go download it, change all all occurrences from 1.21.1 to 1.21. 
Like what? Why would you open an issue for this.

**Comment by jittb** [comment]
Okay, I'll try.

**Comment by jittb** [comment]
I hope you can publish the jar files if possible,Just a suggestion.

**Comment by TreeOfSelf** [comment]
It's literally changing 1.21.1 to 1.21 in a few spots my dude, you can do it. You don't need someone to do it for you.

**Comment by jittb** [comment]
> 它实际上是在几个地方将 1.21.1 更改为 1.21，我的伙计，你可以做到的。你不需要有人为你做这件事。

Many people don't know how to use an ide.Especially for those who do not speak English, their learning will be more difficult.I'll try. Just wanted to say that if you have existing jar files, you can also publish them. Heartfelt thanks

**Comment by TreeOfSelf** [comment]
https://sky.hardcoreanarchy.gay/carpetskyadditions-1.21-5.0.0.jar

You lazy bastard

**Comment by jittb** [comment]
> https://sky.hardcoreanarchy.gay/carpetskyadditions-1.21-5.0.0.jar
> 
> 那么你就在这里！

thank you very much.I learned how to build. Yesterday I went to devlibs to copy the jar file and found it was not working. I was told that was the source. The file should be in lib, ha ha ha
