### ISSUE TITLE
find two serious bugs

### ISSUE THREAD

**Issue by Parseval1** [TreeOfSelf/CarpetSkyAdditions-Reborn#5]
1、Bartering can produce all kinds of enchanted books instead of only soul speed 
2、Sniffer cause the game to crash when they transform sand or gravel into suspicious blocks

**Comment by Seigmannen** [comment]
I can confirm about the piglin bartering. Getting all random enchanted books.

**Comment by Seigmannen** [comment]
[loot_table.json](https://github.com/user-attachments/files/17517013/loot_table.json)

This should be the vanilla piglin bartering json file (1.21.2). Maybe this can be used to update the piglin_bartering.json.

**Comment by TreeOfSelf** [comment]
Yeah, thanks. I did use that and already have it updated. Waiting for Carpet to  release to 1.12.3 and then I will update sometime soon.

**Comment by TreeOfSelf** [comment]
Bartering bug has been addressed, post an actual error for the sniffer problem if you want it fixed.
