### ISSUE TITLE
Trial Spawners

### ISSUE THREAD

**Issue by ryanfrh26** [TreeOfSelf/CarpetSkyAdditions-Reborn#6]
I noticed that Trial Spawners only activate once qnd dont spawn mobs again even after 30 minutes, not sure if its a bug or a feature, would make sense to disable them and keep only breeze spawners and one trial vault/ominous vault per "chamber" generation.

**Comment by TreeOfSelf** [comment]
Might make it eventually so only one breeze spawner, plus a vault and a single ominous trial spawner. Because right now they are a excessive. 
As far as them not spawning mobs again, that is just vanilla behavior.
