### ISSUE TITLE
There is a serious problem.

### ISSUE THREAD

**Issue by mzxyhbl** [TreeOfSelf/CarpetSkyAdditions-Reborn#7]
I added all three files to the mod,Predecessor files were also added as per the tutorial,But when you get into the game,I found that I couldn't create the world.Click no response.

**Comment by TreeOfSelf** [comment]
Run it as a standalone server as workaround for now. I don't run it in singleplayer, so this isn't high priority for me to fix.

**Comment by mzxyhbl** [comment]
> 作为目前的解决方法，将其作为独立服务器运行。我没有运行它在单人，所以这不是我的高优先级修复。

I want to know the reason why the world can't be created.Are these three files in the mod?

**Comment by TreeOfSelf** [comment]
Source code is right there

**Comment by Seigmannen** [comment]
I was able to solve this issue. See my pull request.

**Comment by TreeOfSelf** [comment]
Issue fixed by [Seigmannen](https://github.com/Seigmannen) 
Thanks, a ton. 
If you get a chance, there also is an issue apparently with Sniffers causing a crash when converting gravel/sand to suspicious. But, I wasn't given an error and didn't feel up to recreating it.
